export const GET_ADS_REQUEST = 'GET_ADS_REQ'
export const GET_ADS_SUCCESS = 'GET_ADS_SUCCESS'
export const GET_ADS_FAIL = 'GET_ADS_FAIL'

export const GET_NEW_ADS_REQUEST = 'GET_NEW_ADS_REQUEST'
export const GET_NEW_ADS_SUCCESS = 'GET_NEW_ADS_SUCCESS'
export const GET_NEW_ADS_FAIL = 'GET_NEW_ADS_FAIL'

export const GET_ST_ADS_REQUEST = 'GET_ST_ADS_REQUEST'
export const GET_ST_ADS_SUCCESS = 'GET_ST_ADS_SUCCESS'
export const GET_ST_ADS_FAIL = 'GET_ST_ADS_FAIL'

export const GET_SO_ADS_REQUEST = 'GET_SO_ADS_REQUEST'
export const GET_SO_ADS_SUCCESS = 'GET_SO_ADS_SUCCESS'
export const GET_SO_ADS_FAIL = 'GET_SO_ADS_FAIL'

export const GET_SINGLE_AD_REQUEST = 'GET_SINGLE_AD_REQ'
export const GET_SINGLE_AD_SUCCESS = 'GET_SINGLE_AD_SUCCESS'
export const GET_SINGLE_AD_FAIL = 'GET_SINGLE_AD_FAIL'

export const GET_USERS_ADS_REQUEST = 'GET_USERS_ADS_REQ'
export const GET_USERS_ADS_SUCCESS = 'GET_USERS_ADS_SUCCESS'
export const GET_USERS_ADS_FAIL = 'GET_USERS_ADS_FAIL'

export const AD_CREATE_REQ = 'SHOW_CREATE_REQ'
export const AD_CREATE_SUCCESS = 'SHOW_CREATE_SUCCESS'
export const AD_CREATE_FAIL = 'SHOW_CREATE_FAIL'
export const AD_CREATE_RESET = 'SHOW_CREATE_RESET'

export const AD_DELETE_REQ = 'SHOW_DELETE_REQ'
export const AD_DELETE_SUCCESS = 'SHOW_DELETE_SUCCESS'
export const AD_DELETE_FAIL = 'SHOW_DELETE_FAIL'

export const AD_UPDATE_REQ = 'AD_UPDATE_REQ'
export const AD_UPDATE_SUCCESS = 'AD_UPDATE_SUCCESS'
export const AD_UPDATE_FAIL = 'AD_UPDATE_FAIL'
export const AD_UPDATE_RESET = 'AD_UPDATE_RESET'
